In [2]:
print("Hello Seaborn!")

Hello Seaborn!

Let's import necessary modules

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns

Loading the csv file into a pandas dataframe

In [4]:
dataset_path = "../../DataSource/Social_media_impact_on_life.csv"
df = pd.read_csv(dataset_path)
df.head()

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Overall_Impact
0,232,21,Male,Undergraduate,Other,4.0,Facebook,No,6.7,6.8,Neutral
1,564,23,Female,Undergraduate,Other,1.6,LinkedIn,No,8.6,7.6,Positive
2,788,22,Male,Graduate,Canada,4.6,Instagram,No,6.7,7.0,Neutral
3,686,18,Male,Undergraduate,Other,7.0,Snapchat,Yes,5.4,5.3,Negative
4,608,24,Female,High School,Other,7.5,Facebook,Yes,5.0,4.4,Negative

Basic Data Checks

In [5]:
df.describe()

,Student_ID,Age,Avg_Daily_Usage_Hours,Sleep_Hours_Per_Night,Mental_Health_Score
count,1705.000000,1705.000000,1705.000000,1705.000000,1705.000000
mean,439.510264,20.848094,5.103636,6.598710,6.215132
std,267.058174,1.758557,1.677341,1.207045,1.282678
min,1.000000,18.000000,1.500000,3.800000,4.000000
25%,214.000000,19.000000,3.800000,5.600000,5.000000
50%,427.000000,21.000000,5.100000,6.600000,6.000000
75%,640.000000,22.000000,6.300000,7.500000,7.000000
max,1000.000000,24.000000,8.500000,9.600000,9.000000

In [6]:
null_summary = df.isnull().mean() * 100
null_summary

Student_ID                      0.0
Age                             0.0
Gender                          0.0
Academic_Level                  0.0
Country                         0.0
Avg_Daily_Usage_Hours           0.0
Most_Used_Platform              0.0
Affects_Academic_Performance    0.0
Sleep_Hours_Per_Night           0.0
Mental_Health_Score             0.0
Overall_Impact                  0.0
dtype: float64

## Univariate Analysis

### Age